name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: rileepher
          password: bcab2c69-79a4-4565-884b-77565f47aa1c
      -
        name: DockerHub build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: rileepher/cicdpractice01:lates
