name: workshop1
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3 qq
    - name: flaskTest
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: python server test
      run: |
        python flaskme.py > log.txt 2>&1 &